document:
  name: Linee guida per le competenze di e-leadership
  description: |
    Le Linee guida di e-leadership forniscono un utile strumento per
    definire i principi e le strategie per la mappatura e la valorizzazione
    degli e-leader, la mappatura di possibili linee di intervento, la
    definizione di percorsi e strumenti per la progettazione formativa e linee
    guida specifiche per la misurazione di impatto. 
  tags:
    - competenze digitali
    - linee guida